### ISSUE TITLE
节点搜索中文乱码

### ISSUE THREAD

**Issue by goddesssmile** [grapheco/InteractiveGraph-neo4j#2]
当连接的neo4j数据库是中文名称的节点时，在图搜索器和关系查找器中在输入框输入相应的中文名称无法查询出节点信息，看到后台的日志是中文字符乱码，因此可能是graphServer中的代码编码格式问题，或者有其他我不知道的原因，还请您能够解答下。

**Comment by Airzihao** [comment]
Same as #1 ,see #1 please.
