### ISSUE TITLE
您好，新版本编译可能有些问题

### ISSUE THREAD

**Issue by goddesssmile** [grapheco/InteractiveGraph-neo4j#3]
非常感谢您的回复，您发布的新版本下载之后，部署后连接会产生500错误，经我查看，发现class下面很多代码与之前的版本相比，缺少了很多class文件，尤其是内部类，因此我猜想可能是您的编译发布出了一些问题，因此请您再查看一下，谢谢。

**Comment by Airzihao** [comment]
Thanks for your issue. I update the [release,](https://github.com/grapheco/InteractiveGraph-neo4j/releases) but there seems not any problem with it. 
The ```connector-bolt``` depends on ```connector-neodb```, so maybe you could try to connect to ```connector-neodb``` first, and then connect to ```connector-bolt```.
Hope this solution can help you.
Looking forward to your reply.
Thanks for your try again, and best wishes.

**Comment by goddesssmile** [comment]
Ok,thanks.
另外，我想请教您一下您的源码如何打成war包发布呢，我不会scala编程，源码下载下来后几次打包都会成功，若您有时间还请赐教。

发送自 Windows 10 版邮件应用

发件人: Airzihao
发送时间: 2019年1月14日 20:01
收件人: grapheco/InteractiveGraph-neo4j
抄送: goddesssmile; Author
主题: Re: [grapheco/InteractiveGraph-neo4j] 您好，新版本编译可能有些问题 (#3)

Thanks for your issue. I update the release, but there seems not any problem with it.
The connector-bolt depends on connector-neodb, so maybe you could try to connect to connector-neodb first, and then connect to connector-bolt.
Hope this solution can help you.
Looking forward to your reply.
Thanks for your try again, and best wishes.

**Comment by Airzihao** [comment]
Maybe you can find solution of your package problem in #5 . 
Thanks for your try, and best wishes!
