### ISSUE TITLE
不同节点显示开关

### ISSUE THREAD

**Issue by serse01** [grapheco/InteractiveGraph-neo4j#8]
在example1的红楼梦例子中，右上角的控制面板上是有一个"人物、事件、地点"的节点开关，关闭开关对应的节点就会隐藏，我查看了honglou.json发现有一个categories字典，删除改字典后这个功能就会消失。现在我想在连接neo4j的时候也实现这个功能，但是neo4j导出的数据中是不包含categories这个字典的，而且在neo4j中好像无法添加这种类型的字典，那么应该如何实现呢？

**Comment by HC-teemo** [comment]
label

**Comment by serse01** [comment]
不好意思能具体描述一下吗，label是指在neo4j的节点中加入label属性吗？

**Comment by serse01** [comment]
> label

我给节点添加了label属性，但是并没有恢复这个功能

**Comment by HC-teemo** [comment]
不是加label属性，是加label

**Comment by serse01** [comment]
> 不是加label属性，是加label

我新增的一个名为categories的label，为这个label添加了book_name="书名", chapter="章名", subject="节名"，3个属性，但是还是无法实现这个功能，是哪里做错了吗？请原谅我的愚钝，详细教导一些可以吗？万分感谢！

**Comment by HC-teemo** [comment]
例如Neo4j中有person,location,event这个label，那么igraph连接neo4j后就会显示这三个类型的开关，不需要额外做操作。

**Comment by serse01** [comment]
> 例如Neo4j中有person,location,event这个label，那么igraph连接neo4j后就会显示这三个类型的开关，不需要额外做操作。

十分感谢您的回答，但是我的Neo4j中已经存在book_name, chapter, subject,object和content这5个label了,但是连接到igraph后并没有显示任何类型的开关,请问这是什么原因呢?

**Comment by serse01** [comment]
> > 例如Neo4j中有person,location,event这个label，那么igraph连接neo4j后就会显示这三个类型的开关，不需要额外做操作。
> 
> 十分感谢您的回答，但是我的Neo4j中已经存在book_name, chapter, subject,object和content这5个label了,但是连接到igraph后并没有显示任何类型的开关,请问这是什么原因呢?

请问这样的话该怎么解决呢

**Comment by HC-teemo** [comment]
请问你的数据量大约多少

**Comment by serse01** [comment]
> 请问你的数据量大约多少

不多,大概100多个

**Comment by HC-teemo** [comment]
> > 请问你的数据量大约多少
> 
> 
> 
> 不多,大概100多个
> 
> 

好的，明天我排查一下

**Comment by serse01** [comment]
好的,谢谢

**Comment by serse01** [comment]
> > > 请问你的数据量大约多少
> > 
> > 
> > 不多,大概100多个
> 
> 好的，明天我排查一下

新年快乐，请问排查好问题了吗，我这边还是显示不了节点开关

**Comment by serse01** [comment]
麻烦了，我这边需要尽快使用

**Comment by HC-teemo** [comment]
> 麻烦了，我这边需要尽快使用

确实存在这样的问题，感谢您的发现指出，我们尽快修复，大概这两天会打包新版本

**Comment by serse01** [comment]
> > 麻烦了，我这边需要尽快使用
> 
> 确实存在这样的问题，感谢您的发现指出，我们尽快修复，大概这两天会打包新版本

好的，辛苦您了，万分感谢！

**Comment by HC-teemo** [comment]
该问题已修复，请下载最新的InteractiveGraph文件替换旧文件，[链接](https://github.com/grapheco/InteractiveGraph/releases/tag/0.3.3)。

**Comment by serse01** [comment]
> 该问题已修复，请下载最新的InteractiveGraph文件替换旧文件，[链接](https://github.com/grapheco/InteractiveGraph/releases/tag/0.3.3)。

已经看到效果了，万分感谢！
